server:
  port: 8082

spring:
  datasource:
    url: ${CUSTOMER_DB_URL:jdbc:mysql://localhost:3306/customer_db?createDatabaseIfNotExist=true}
    username: root
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

security:
  jwt:
    secret: ${JWT_SECRET}
    issuer: enterprise-banking-auth-service

springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html