server:
  port: 8084

spring:
  datasource:
    url: ${TRANSACTION_DB_URL:jdbc:mysql://localhost:3306/transaction_db?createDatabaseIfNotExist=true}
    username: root
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    open-in-view: false

    properties:
      hibernate:
        format_sql: true

  cloud:
    circuitbreaker:
      resilience4j:
        disable-time-limiter: true

      bulkhead:
        resilience4j:
          enabled: false


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}


security:
  jwt:
    secret: ${JWT_SECRET}
    issuer: enterprise-banking-auth-service


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  tracing:
    sampling:
      probability: 1.0

    export:
      zipkin:
        endpoint: ${ZIPKIN_URL:http://127.0.0.1:9411/api/v2/spans}


internal:
  service:
    secret: ${INTERNAL_SERVICE_SECRET}


resilience4j:
  circuitbreaker:
    instances:
      accountService:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        automaticTransitionFromOpenToHalfOpenEnabled: true

  retry:
    instances:
      accountService:
        maxAttempts: 2
        waitDuration: 500ms

        retryExceptions:
          - com.enterprisebank.transaction.exception.AccountServiceUnavailableException

        ignoreExceptions:
          - org.springframework.web.client.RestClientResponseException


springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html